---
version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    minor-actions-dependencies:
      # pip: Only group patch updates
      update-types: [patch]
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    minor-actions-dependencies:
      # GitHub Actions: Only group minor and patch updates
      update-types: [minor, patch]
